-- ClickPet Institutional Investor Database Seed
-- Execute after schemas.sql
-- PostgreSQL 14+

BEGIN;

SET search_path TO clickpet_institutional, public;

-- Recreate ClickPet seed data to keep this script idempotent in development/staging.
DELETE FROM companies WHERE slug = 'clickpet';

INSERT INTO companies (
  id, name, slug, slogan, short_description, institutional_description,
  business_context, business_model_summary, target_audience, market_segment,
  positioning, value_proposition, current_stage, headquarters_country,
  website_url, app_status, visibility, metadata
) VALUES (
  '11111111-1111-1111-1111-111111111111',
  'ClickPet',
  'clickpet',
  'Tudo o que você precisa, a um click de distância',
  'Plataforma B2B2C para digitalizar pet shops independentes, conectando consumidores, lojistas e serviços pet em uma experiência unificada.',
  'A ClickPet é uma plataforma digital criada para transformar pet shops independentes em operações digitais, oferecendo aplicativo para consumidores, painel administrativo para lojistas, catálogo digital, gestão de pedidos, serviços, marketplace regional e recursos de logística e atendimento.',
  'O mercado pet brasileiro é grande e recorrente, mas muitos pequenos e médios pet shops ainda operam vendas por WhatsApp, Instagram e atendimento manual, com baixa padronização, baixa eficiência operacional e pouca presença digital estruturada.',
  'Modelo baseado principalmente em comissão sobre vendas realizadas na plataforma, com possibilidade de expansão para planos premium, publicidade interna, serviços financeiros, logística integrada e ferramentas de marketing para lojistas.',
  'Investidores, pequenos e médios pet shops independentes, clínicas, hospitais veterinários, prestadores de serviços pet e consumidores finais que buscam compra e atendimento pet com conveniência.',
  'Mercado pet, marketplace vertical, delivery local, serviços agendados e digitalização de negócios independentes.',
  'Parceiro tecnológico dos pet shops independentes, não concorrente direto dos lojistas. A empresa busca fortalecer a competitividade local contra grandes redes, marketplaces e apps generalistas.',
  'Centralizar produtos, serviços, agendamentos, entrega e gestão operacional em uma plataforma especializada para o ecossistema pet.',
  'pre_seed',
  'Brasil',
  NULL,
  'MVP concluído, aplicativo publicado, plataforma operacional, website operacional e primeiros pet shops utilizando a solução.',
  'investor',
  '{"seed_version":"1.0","focus":"investor consultation","ai_role":"natural language layer over structured data"}'::jsonb
);

INSERT INTO institutional_sources (company_id, title, source_type, file_name, source_reference, description, reference_date, version, reliability_notes, metadata)
VALUES
('11111111-1111-1111-1111-111111111111','ClickPet PitchDeck','pitch_deck','ClickPet PitchDeck.pdf','uploaded_file','Material de pitch com problema, solução, nascimento da ClickPet, mercado, posicionamento competitivo, operação, estratégia B2B2C e equipe.',NULL,'1.0','Material institucional fornecido pelo usuário.', '{"pages":9}'::jsonb),
('11111111-1111-1111-1111-111111111111','ClickPet - Análise de Concorrência','competitive_analysis','ClickPet - Análise de Concorrência.pdf','uploaded_file','Análise estratégica de concorrência da ClickPet frente a delivery generalista, e-commerce pet nacional, redes varejistas e marketplace pet.',NULL,'1.0','Material institucional fornecido pelo usuário.', '{"pages":11}'::jsonb),
('11111111-1111-1111-1111-111111111111','ClickPet - Apresentação de Projeto','project_presentation','ClickPet - Apresentação de Projeto.pdf','uploaded_file','Apresentação do produto com módulos de experiência de compra, dashboard do parceiro, pedidos, atendimento, promoções, logística, licenciamento e parametrização operacional.',NULL,'1.0','Material institucional fornecido pelo usuário.', '{"pages":12}'::jsonb),
('11111111-1111-1111-1111-111111111111','Investment Memo ClickPet','investment_memo',NULL,'user_provided_text','Memo de investimento com rodada Pré-Seed, valuation, problema, solução, mercado, modelo de negócio, tração, projeções, uso de recursos, riscos e visão de longo prazo.',NULL,'1.0','Texto fornecido diretamente pelo usuário.', '{}'::jsonb);

-- =========================
-- CONTENT SECTIONS
-- =========================

INSERT INTO content_sections (company_id, source_id, category, title, summary, full_content, display_order, page_reference, section_reference, tags)
VALUES
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'company','Executive Summary','A ClickPet digitaliza pet shops independentes com uma infraestrutura B2B2C pronta para operação.','O ClickPet é uma plataforma B2B2C desenvolvida para digitalizar pet shops independentes, oferecendo infraestrutura completa para vendas online, gestão de pedidos e conexão direta com consumidores. A empresa está em estágio Pré-Seed, com MVP concluído, aplicativo publicado, plataforma operacional e primeiros estabelecimentos utilizando a solução.',1,NULL,'executive_summary',ARRAY['empresa','resumo','investidor']),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'problem','Problema de Mercado','Pet shops independentes ainda dependem de canais informais e baixa estrutura digital.','Grande parte dos pet shops independentes enfrenta ausência de e-commerce, custos elevados para desenvolver tecnologia própria, dependência de atendimento manual, dificuldade de fidelização, baixa eficiência operacional e presença digital limitada. Como consequência, perdem competitividade para grandes redes e marketplaces consolidados.',2,NULL,'problema',ARRAY['problema','mercado','petshops']),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'solution','Solução ClickPet','Plataforma completa para transformar qualquer pet shop em uma operação digital.','A solução contempla aplicativo para consumidores, painel administrativo para lojistas, gestão de pedidos, catálogo digital, marketplace regional, integração entre consumidores e estabelecimentos e tecnologia pronta para operação.',3,NULL,'solucao',ARRAY['solucao','produto','plataforma']),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='ClickPet PitchDeck'),'market','Mercado em expansão','O setor pet cresce, mas a experiência ainda é analógica e fragmentada.','O Pitch Deck apresenta o mercado pet como um setor em expansão, pronto para inovação digital, com alta demanda e baixa digitalização. O material destaca 3º maior mercado de petshop do mundo, 10% de crescimento ao ano, R$ 78 bilhões de faturamento anual e 160 milhões de pets no país.',4,'p.5','crescimento_do_mercado',ARRAY['mercado','crescimento','dados']),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='ClickPet - Análise de Concorrência'),'competition','Panorama competitivo','A ClickPet atua nas três frentes concorrenciais simultaneamente.','A análise de concorrência divide o mercado em delivery generalista, e-commerce nacional pet e plataforma especializada pet. A ClickPet é posicionada como a única plataforma que combina gestão completa do pet shop, delivery, serviços agendados e marketplace dedicado.',5,'p.3','tres_frentes_concorrencia',ARRAY['concorrencia','posicionamento','benchmark']),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='ClickPet - Apresentação de Projeto'),'product','Produto e operação','O produto combina experiência de compra, dashboard, pedidos, atendimento, promoções, logística e parametrização do negócio.','A apresentação do projeto descreve a plataforma digital como integração de produtos e serviços para pets com entrega sob demanda. O material detalha módulos de filtragem de produtos, tela de produto, dashboard do parceiro, gestão de pedidos, agenda de atendimento, cupons, entregadores, licenciamento e configurações operacionais.',6,NULL,'produto',ARRAY['produto','dashboard','modulos']),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'funding','Rodada Pré-Seed','Rodada proposta de R$ 500 mil com valuation pré-money de R$ 3,2 milhões.','A rodada proposta é Pré-Seed, com valuation pré-money de R$ 3.200.000, captação pretendida de R$ 500.000, valuation pós-money de R$ 3.700.000 e participação ofertada de 13,5%.',7,NULL,'rodada',ARRAY['rodada','valuation','captação']),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'vision','Visão de longo prazo','Construir a principal infraestrutura digital para pet shops independentes no Brasil.','A missão de longo prazo é consolidar um ecossistema que conecte consumidores, estabelecimentos e tecnologia em uma plataforma única, ampliando a competitividade das lojas parceiras e acompanhando a evolução do mercado pet brasileiro.',8,NULL,'visao_longo_prazo',ARRAY['visao','estrategia','longo-prazo']);

-- =========================
-- INVESTMENT
-- =========================

INSERT INTO investment_theses (company_id, source_id, title, thesis_summary, thesis_detail, market_reason, product_reason, traction_reason, timing_reason, investor_takeaway, display_order)
VALUES
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'Digitalização vertical do pet shop independente','A ClickPet captura uma lacuna entre um mercado pet grande, recorrente e pulverizado e a baixa maturidade digital dos pet shops independentes.','A tese combina mercado recorrente, dor clara, produto já desenvolvido, baixo custo de entrada para lojistas e potencial de escala regional e nacional. A plataforma atua como infraestrutura digital para pequenos e médios pet shops, não como substituta desses lojistas.','O mercado pet brasileiro possui grande volume, recorrência de compra e forte presença de pequenos e médios estabelecimentos ainda pouco digitalizados.','O produto já contempla aplicativo, painel administrativo, catálogo, pedidos, serviços, promoções, logística, licenciamento e parametrização operacional.','MVP concluído, aplicativo publicado, plataforma operacional, website em funcionamento e primeiros estabelecimentos usando a solução.','O momento é favorável porque consumidores buscam conveniência e negócios locais precisam competir digitalmente com redes maiores e marketplaces.','A oportunidade está em financiar aquisição comercial e expansão de uma plataforma cujo risco tecnológico inicial já foi reduzido.',1),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='ClickPet - Análise de Concorrência'),'Unificação de uma jornada fragmentada','A vantagem competitiva vem da integração de compra, serviço, agenda, entrega e gestão em uma única plataforma especializada.','Apps generalistas não são especializados no setor pet; grandes redes focam em venda própria; marketplaces pet não resolvem completamente agenda, logística e operação local. A ClickPet propõe uma camada vertical completa.','O setor possui demanda, mas a experiência de cliente ainda é distribuída entre WhatsApp, redes sociais, sites, apps generalistas e atendimento manual.','A plataforma foi desenhada para centralizar a jornada do consumidor e a operação do lojista.','A existência de um produto funcional permite validação comercial com menor risco de construção.', 'A digitalização vertical ainda está em estágio inicial nos nichos de serviço pet.', 'Para investidores, a defesa está na especialização vertical e na posição de parceiro dos pet shops locais.',2);

INSERT INTO investment_rounds (company_id, source_id, round_name, stage, currency, pre_money_valuation, target_raise_amount, post_money_valuation, equity_offered_percent, valuation_rationale, round_objective, status)
VALUES
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'Pré-Seed','pre_seed','BRL',3200000.00,500000.00,3700000.00,13.50,'Valuation proposto considera produto desenvolvido, tecnologia proprietária, aplicativo publicado, plataforma operacional, infraestrutura própria, validação inicial da solução e potencial de escalabilidade.','Acelerar aquisição de clientes, fortalecer evolução do produto e validar expansão comercial em escala.','proposed');

INSERT INTO funding_use_allocations (round_id, allocation_area, allocation_percent, estimated_amount, purpose, expected_impact, display_order)
VALUES
((SELECT id FROM investment_rounds WHERE company_id='11111111-1111-1111-1111-111111111111' AND round_name='Pré-Seed'),'Produto e tecnologia',40.00,200000.00,'Desenvolvimento de produto, evolução da plataforma, melhorias técnicas, automações e infraestrutura.','Aumentar robustez do produto, reduzir fricção operacional e preparar a plataforma para escala.',1),
((SELECT id FROM investment_rounds WHERE company_id='11111111-1111-1111-1111-111111111111' AND round_name='Pré-Seed'),'Marketing e aquisição de clientes',30.00,150000.00,'Campanhas, canais digitais, aquisição de lojistas e consumidores e validação de canais de crescimento.','Acelerar entrada de pet shops e fortalecer reconhecimento regional da marca.',2),
((SELECT id FROM investment_rounds WHERE company_id='11111111-1111-1111-1111-111111111111' AND round_name='Pré-Seed'),'Expansão comercial',20.00,100000.00,'Prospecção ativa, parcerias, operação comercial e expansão para novas regiões.','Validar modelo comercial e aumentar base de parceiros.',3),
((SELECT id FROM investment_rounds WHERE company_id='11111111-1111-1111-1111-111111111111' AND round_name='Pré-Seed'),'Capital de giro',10.00,50000.00,'Reserva operacional para sustentação das atividades durante a fase de validação e crescimento.','Maior segurança financeira na execução da rodada.',4);

-- =========================
-- MARKET, PROBLEM, SOLUTION
-- =========================

INSERT INTO market_opportunities (company_id, source_id, title, market_context, opportunity_summary, target_segment, timing_factor, scalability_factor, investor_relevance, display_order)
VALUES
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='ClickPet - Análise de Concorrência'),'Mercado pet brasileiro pulverizado','Material de análise aponta R$ 78 bilhões em faturamento em 2025, 168 milhões de animais estimados, 48,7% de market share em PME pet shops e crescimento previsto de 9,6% para 2026.','A oportunidade-chave é atuar nos pequenos e médios pet shops locais, que representam parte relevante do mercado e ainda não possuem plataforma especializada de gestão e delivery integrados.','Pequenos e médios pet shops independentes e negócios locais do setor pet.','Consumidores tratam pets como membros da família e buscam conveniência, enquanto a experiência digital ainda é fragmentada.','Modelo com potencial de expansão regional por parceiros locais, marketplace e padronização de operação digital.', 'Mostra que a ClickPet endereça um segmento grande, recorrente e ainda pouco servido por soluções verticais completas.',1),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'Digitalização acessível para negócios independentes','Grandes redes já possuem presença digital, mas milhares de pequenos e médios pet shops dependem de canais informais.','A ClickPet reduz a barreira tecnológica ao oferecer uma solução pronta para operação, sem exigir que cada lojista desenvolva sistemas próprios.','Pet shops independentes com baixa maturidade digital.','A digitalização do consumo e a busca por conveniência aumentam a pressão competitiva sobre lojas locais.','A solução pode ser replicada em novas regiões mantendo foco vertical no setor pet.', 'A tese depende de transformar uma dor operacional real em receita transacional e recorrente.',2);

INSERT INTO market_problems (company_id, source_id, title, problem_summary, problem_detail, affected_audience, severity_level, business_impact, evidence_notes, display_order)
VALUES
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='ClickPet PitchDeck'),'Tempo perdido e canais múltiplos','Donos de pets precisam resolver uma única necessidade em múltiplos canais.','A experiência atual exige alternar entre lojas, WhatsApp, redes sociais, sites, ligações e atendimento manual para compra, agendamento e acompanhamento.', 'Consumidores finais e pet shops que precisam atender manualmente.', 'medium','Reduz conversão, aumenta esforço do cliente e dificulta recorrência.', 'Pitch Deck: problema de tempo perdido e experiência fragmentada.',1),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'Ausência de e-commerce estruturado','Muitos pet shops independentes não possuem estrutura própria de venda online.','A falta de e-commerce limita alcance, controle de catálogo, disponibilidade de produtos e capacidade de competir com redes maiores.', 'Pet shops independentes.', 'high','Perda de competitividade e dependência de vendas manuais.', 'Investment Memo: ausência de estrutura de e-commerce.',2),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'Dependência de WhatsApp e Instagram','Vendas e atendimento ainda ocorrem por canais informais e pouco escaláveis.','A dependência desses canais gera atendimento manual, baixa padronização, baixa visibilidade de dados e pouca automação.', 'Lojistas e consumidores.', 'high','Dificulta escala, métricas, fidelização e previsibilidade operacional.', 'Investment Memo e análise concorrencial destacam dependência de WhatsApp e processos manuais.',3),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='ClickPet PitchDeck'),'Falta de transparência','Consumidores têm dificuldade em comparar preços, disponibilidade e qualidade.','A ausência de um ambiente centralizado limita comparação entre produtos, serviços, avaliações e disponibilidade real.', 'Consumidores finais.', 'medium','Gera incerteza na decisão de compra e reduz confiança.', 'Pitch Deck: falta de transparência em preços, disponibilidade e qualidade.',4),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'Baixa eficiência operacional','Processos manuais reduzem produtividade e dificultam acompanhamento de pedidos, serviços e entregas.','Sem painel operacional, lojistas têm dificuldade para gerir pedidos, agenda, catálogo, promoções, entregadores, métricas e regras de entrega.', 'Pet shops, clínicas e serviços pet.', 'high','Eleva erro operacional, tempo de resposta e custo de gestão.', 'Investment Memo e Apresentação de Projeto.',5);

INSERT INTO solutions (company_id, source_id, title, solution_summary, solution_detail, delivered_value, implementation_status, display_order)
VALUES
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='ClickPet PitchDeck'),'Tudo em um único lugar','Produtos, serviços e atendimentos integrados em uma jornada única.','A ClickPet centraliza lojas, produtos, serviços, agendamentos e comparação de preços, reduzindo a fragmentação da experiência.', 'Conveniência para consumidores e padronização para lojistas.', 'mvp_completed',1),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'Plataforma pronta para operação','Infraestrutura completa para vendas online, gestão de pedidos e conexão com consumidores.','Inclui aplicativo, painel administrativo, catálogo digital, marketplace regional, gestão de pedidos e integração entre consumidores e estabelecimentos.', 'Reduz custo e tempo de digitalização para pet shops independentes.', 'operational_platform',2),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='ClickPet PitchDeck'),'Transparente e confiável','Comparação clara e avaliações reais entre produtos, lojas e serviços.','A plataforma busca permitir escolha melhor informada pelo usuário, aumentando confiança e qualidade percebida.', 'Aumenta confiança, conversão e retenção.', 'presented_in_product',3),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='ClickPet - Apresentação de Projeto'),'Gestão operacional para parceiros','Dashboard operacional para vendas, pedidos, produtos, agenda, promoções, entregadores e parametrização.','O painel do parceiro concentra métricas em tempo real, gestão de catálogo, controle de pedidos, agenda de atendimento, cupons, logística e configurações de operação.', 'Melhora eficiência, reduz erros e aumenta retenção do lojista.', 'presented_in_product',4);

-- =========================
-- PRODUCT MODULES AND FEATURES
-- =========================

INSERT INTO product_modules (company_id, source_id, module_name, module_slug, module_summary, module_detail, user_group, business_value, status, display_order)
VALUES
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='ClickPet - Apresentação de Projeto'),'Aplicativo do consumidor','app-consumidor','Experiência de compra e descoberta para consumidores finais.','Permite encontrar produtos e serviços pet, filtrar catálogo, visualizar detalhes, avaliações, preço, quantidade e produtos relacionados.', 'Consumidor final','Aumenta conversão e recorrência de compra.', 'operational_or_presented',1),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='ClickPet - Apresentação de Projeto'),'Dashboard do parceiro','dashboard-parceiro','Painel administrativo para centralizar vendas, pedidos e gestão de produtos.','Oferece controle simples e visão consolidada do negócio, com métricas em tempo real, catálogo, preços e insights visuais.', 'Pet shop parceiro','Melhora eficiência e retenção da plataforma.', 'operational_or_presented',2),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='ClickPet - Apresentação de Projeto'),'Gestão de pedidos','gestao-pedidos','Controle completo de pedidos com status, histórico e ciclo de entrega.','Centraliza informações de pagamento, cliente, valor, status e volume para suporte à tomada de decisão.', 'Pet shop parceiro','Reduz erros e melhora tempo de resposta.', 'operational_or_presented',3),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='ClickPet - Apresentação de Projeto'),'Gestão de fluxo de atendimento','gestao-atendimento','Painel para controle de horários e serviços agendados.','Permite visualizar ocupação da agenda, status de compromissos e volume de agendamentos realizados versus concluídos.', 'Pet shop, clínica e serviço pet','Aumenta pontualidade, experiência do cliente e retenção.', 'operational_or_presented',4),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='ClickPet - Apresentação de Projeto'),'Gestão de promoções','gestao-promocoes','Criação e controle de campanhas de desconto e cupons.','Permite configurar cupons de primeira compra, influenciadores, datas sazonais, validade, limite de uso e valor mínimo.', 'Pet shop parceiro','Aumenta aquisição, conversão e performance de campanhas.', 'operational_or_presented',5),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='ClickPet - Apresentação de Projeto'),'Gestão logística','gestao-logistica','Cadastro e controle de parceiros de entrega.','Permite registrar entregadores, CNH, veículos, dados cadastrais e contatos para demanda de leva e traz.', 'Pet shop parceiro e entregadores','Apoia confiabilidade, organização e segurança operacional.', 'operational_or_presented',6),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='ClickPet - Apresentação de Projeto'),'Licenciamento e sustentabilidade','licenciamento-sustentabilidade','Controle do vínculo entre pet shop e plataforma ClickPet.','Dá visibilidade sobre custo fixo de software, continuidade operacional, cota de produtos e serviços, renovação automática e upgrades.', 'Pet shop parceiro','Apoia receita recorrente e expansão de planos.', 'operational_or_presented',7),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='ClickPet - Apresentação de Projeto'),'Parametrização operacional','parametrizacao-operacional','Configuração de regras fundamentais da operação.','Permite configurar contato, localização, políticas de frete, valor mínimo de pedido, horários semanais, raio de entrega e meios de pagamento.', 'Pet shop parceiro','Viabiliza operação local com regras próprias.', 'operational_or_presented',8);

INSERT INTO product_features (company_id, module_id, source_id, feature_name, feature_slug, feature_summary, feature_detail, user_benefit, investor_relevance, status, display_order)
VALUES
('11111111-1111-1111-1111-111111111111',(SELECT id FROM product_modules WHERE module_slug='app-consumidor'),(SELECT id FROM institutional_sources WHERE title='ClickPet - Apresentação de Projeto'),'Filtragem de produtos','filtragem-produtos','Busca inteligente por espécie, raça, faixa de preço e categorias.','Sistema de filtragem desenvolvido para otimizar a busca do usuário e facilitar escolha do produto adequado.', 'Menos tempo procurando e mais precisão na compra.', 'Melhora experiência e taxa de conversão.', 'presented',1),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM product_modules WHERE module_slug='app-consumidor'),(SELECT id FROM institutional_sources WHERE title='ClickPet - Apresentação de Projeto'),'Tela de produto otimizada','tela-produto-otimizada','Página com informações claras, variações, avaliações e CTA direto.','Estrutura com preço, quantidade, prova social e produtos relacionados para incentivar upsell e cross-sell.', 'Decisão rápida com menor fricção.', 'Aumenta conversão e ticket médio.', 'presented',2),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM product_modules WHERE module_slug='dashboard-parceiro'),(SELECT id FROM institutional_sources WHERE title='ClickPet - Apresentação de Projeto'),'Métricas em tempo real','metricas-tempo-real','Indicadores de vendas, pedidos e produtos no dashboard.','Permite visão consolidada e tomada de decisão baseada em dados.', 'Gestão mais prática e objetiva.', 'Aumenta valor percebido pelo lojista e retenção.', 'presented',3),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM product_modules WHERE module_slug='gestao-pedidos'),(SELECT id FROM institutional_sources WHERE title='ClickPet - Apresentação de Projeto'),'Segmentação por status de pedido','segmentacao-status-pedido','Organização dos pedidos por status para priorização.','Ajuda a controlar ciclo de entrega, pagamento, cliente, valor e histórico.', 'Reduz atrasos e melhora previsibilidade.', 'Aumenta eficiência operacional.', 'presented',4),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM product_modules WHERE module_slug='gestao-atendimento'),(SELECT id FROM institutional_sources WHERE title='ClickPet - Apresentação de Projeto'),'Agenda por ciclo de vida','agenda-ciclo-vida','Status Pendente, Confirmado, Concluído ou Cancelado.','Permite medir comparecimento, volume de agendamentos e desempenho mensal.', 'Melhor organização do atendimento.', 'Expande a plataforma para serviços, não apenas produtos.', 'presented',5),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM product_modules WHERE module_slug='gestao-promocoes'),(SELECT id FROM institutional_sources WHERE title='ClickPet - Apresentação de Projeto'),'Cupons e campanhas','cupons-campanhas','Configuração de gatilhos, prazos, limites de uso e regras de ativação.','Inclui cupons de primeira compra, parcerias com influenciadores e datas sazonais.', 'Mais controle sobre ações promocionais.', 'Apoia aquisição e geração de demanda.', 'presented',6),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM product_modules WHERE module_slug='gestao-logistica'),(SELECT id FROM institutional_sources WHERE title='ClickPet - Apresentação de Projeto'),'Cadastro de entregadores','cadastro-entregadores','Registro de dados de entregadores, CNH e veículos.','Centraliza dados cadastrais, frota, contatos e manutenção da base logística.', 'Mais segurança e organização na entrega.', 'Fortalece logística local e confiabilidade da operação.', 'presented',7),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM product_modules WHERE module_slug='parametrizacao-operacional'),(SELECT id FROM institutional_sources WHERE title='ClickPet - Apresentação de Projeto'),'Regras de frete e raio de entrega','regras-frete-raio-entrega','Configuração de alcance, taxa, horários e valor mínimo.','Permite adaptar a operação à realidade de cada pet shop e região.', 'Operação mais personalizada e previsível.', 'Facilita escala regional mantendo flexibilidade local.', 'presented',8);

-- =========================
-- TRACTION, REVENUE, GROWTH
-- =========================

INSERT INTO traction_metrics (company_id, source_id, metric_name, metric_slug, value_type, boolean_value, text_value, unit, context, investor_relevance)
VALUES
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'MVP concluído','mvp-concluido','boolean',TRUE,'MVP concluído',NULL,'Produto inicial finalizado antes da captação externa.','Reduz risco tecnológico inicial.'),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'Aplicativo publicado','aplicativo-publicado','boolean',TRUE,'Aplicativo publicado',NULL,'Aplicativo já disponibilizado segundo o memo.', 'Demonstra execução de produto.'),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'Plataforma operacional','plataforma-operacional','boolean',TRUE,'Plataforma operacional',NULL,'Plataforma funcional e utilizável.', 'Indica prontidão para validação comercial.'),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'Website operacional','website-operacional','boolean',TRUE,'Website operacional',NULL,'Website em funcionamento.', 'Complementa presença institucional e aquisição.'),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'Primeiros pet shops utilizando','primeiros-petshops-utilizando','boolean',TRUE,'Primeiros estabelecimentos utilizando a solução',NULL,'Primeiros pet shops usando a plataforma.', 'Validação inicial de uso.'),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='ClickPet - Análise de Concorrência'),'Faturamento mercado pet 2025','faturamento-mercado-pet-2025','money',NULL,'R$ 78 bilhões','BRL','Mercado pet brasileiro estimado no material de concorrência.', 'Dimensiona a oportunidade de mercado.'),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='ClickPet - Análise de Concorrência'),'Market share PME pet shops','market-share-pme-petshops','percentage',NULL,'48,7%','percentual','Percentual do mercado em pequenos e médios pet shops segundo material de concorrência.', 'Indica relevância do segmento-alvo.'),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='ClickPet - Análise de Concorrência'),'Crescimento previsto 2026','crescimento-previsto-2026','percentage',NULL,'9,6%','percentual','Crescimento previsto para 2026 no material de concorrência.', 'Indica timing favorável.');

UPDATE traction_metrics SET money_value=78000000000.00 WHERE metric_slug='faturamento-mercado-pet-2025';
UPDATE traction_metrics SET percentage_value=48.7000 WHERE metric_slug='market-share-pme-petshops';
UPDATE traction_metrics SET percentage_value=9.6000 WHERE metric_slug='crescimento-previsto-2026';

INSERT INTO revenue_streams (company_id, source_id, stream_name, stream_slug, description, monetization_logic, maturity_stage, priority_level, investor_relevance)
VALUES
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'Comissão sobre vendas','comissao-sobre-vendas','Principal fonte de receita prevista: comissão sobre vendas realizadas dentro da plataforma.','Receita acompanha o aumento do volume transacionado pelas lojas parceiras.', 'core_planned',10,'Modelo escalável vinculado ao GMV.'),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'Planos premium','planos-premium','Monetização futura com planos pagos para lojistas.','Pode destravar recursos adicionais, limites maiores, analytics e suporte.', 'future',8,'Cria potencial de receita recorrente.'),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'Publicidade interna','publicidade-interna','Receita futura com destaque de produtos, lojas e campanhas internas.','Lojistas podem pagar por visibilidade e conversão dentro do marketplace.', 'future',6,'Aumenta monetização por lojista sem depender apenas de comissão.'),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'Serviços financeiros','servicos-financeiros','Possibilidade futura de serviços financeiros para lojistas e consumidores.','Pode incluir meios de pagamento, antecipação, crédito ou soluções financeiras relacionadas.', 'future',5,'Amplia margem e profundidade do ecossistema.'),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'Logística integrada','logistica-integrada','Monetização futura associada à operação logística e entrega local.','Pode capturar parte do valor de entrega, frota parceira ou serviços de leva e traz.', 'future',7,'Fortalece controle da experiência e gera nova linha de receita.'),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'Ferramentas de marketing para lojistas','ferramentas-marketing-lojistas','Recursos pagos para campanhas, cupons, CRM e performance comercial.','Lojistas podem usar ferramentas para aquisição, recorrência e fidelização.', 'future',7,'Aumenta retenção e ARPU de parceiros.');

INSERT INTO growth_strategies (company_id, source_id, strategy_name, strategy_summary, strategy_detail, channel, objective, expected_outcome, display_order)
VALUES
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'Prospecção comercial ativa','Abordagem direta a pet shops independentes para aquisição inicial.','Contato com lojistas, demonstração da plataforma, onboarding e validação do modelo comercial.', 'vendas diretas','Alcançar massa crítica inicial de lojas parceiras.', 'Aumento da base de pet shops cadastrados.',1),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'Parcerias estratégicas','Construção de canais de expansão por parceiros locais e setoriais.','Parcerias podem ampliar entrada em novas regiões, serviços e ecossistema pet.', 'parcerias','Reduzir custo de aquisição e ampliar capilaridade.', 'Expansão regional mais eficiente.',2),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'Marketing digital','Campanhas para atrair lojistas e consumidores.','Uso de canais digitais para aquisição, awareness, educação de mercado e geração de demanda.', 'marketing digital','Fortalecer canais de aquisição.', 'Aumento de cadastros e reconhecimento da marca.',3),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'Programa de indicação','Estimular indicação entre lojistas, consumidores e parceiros.','Modelo de crescimento baseado em rede local e recomendação.', 'referral','Reduzir CAC e acelerar aquisição.', 'Crescimento orgânico e validação de confiança.',4),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'Ações regionais de expansão','Entrada planejada em novas regiões com foco local.','Expansão por regiões prioritárias, combinando prospecção, parceiros, marketing e onboarding.', 'regional','Validar replicabilidade do modelo.', 'Escala geográfica progressiva.',5);

INSERT INTO growth_targets (company_id, source_id, target_name, period_type, period_label, target_metric, target_value, target_unit, target_description, strategic_relevance, display_order)
VALUES
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'100 pet shops ativas','date','Até dezembro','pet shops ativas',100,'lojas','Meta operacional de atingir 100 pet shops ativas até dezembro.', 'Valida aquisição inicial e massa crítica local.',1),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'300 lojas no ano 2','year','Ano 2','lojas cadastradas',300,'lojas','Projeção de 300 lojas no segundo ano.', 'Demonstra ambição de expansão pós-validação.',2),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'700 lojas no ano 3','year','Ano 3','lojas cadastradas',700,'lojas','Projeção de 700 lojas no terceiro ano.', 'Indica escala regional/nacional em desenvolvimento.',3),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'Mais de 2.000 lojas no ano 5','year','Ano 5','lojas cadastradas',2000,'lojas','Projeção de mais de 2.000 lojas cadastradas no quinto ano.', 'Tese de escala nacional.',4);

-- =========================
-- COMPETITION
-- =========================

INSERT INTO competitors (company_id, source_id, name, slug, competitor_type, description, market_position)
VALUES
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='ClickPet - Análise de Concorrência'),'iFood','ifood','delivery_app','Plataforma de delivery generalista que atende pet shops como mais uma categoria, sem gestão dedicada ao setor pet.','Líder em delivery generalista no Brasil.'),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='ClickPet - Análise de Concorrência'),'Aiqfome','aiqfome','delivery_app','Plataforma generalista do Grupo Magalu com presença no interior do Brasil.','Delivery generalista regional.'),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='ClickPet - Análise de Concorrência'),'Grupo Petz-Cobasi','grupo-petz-cobasi','retail_chain','Grande rede varejista pet com presença física e digital, focada principalmente em venda de produtos próprios.','Grande rede varejista nacional.'),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='ClickPet - Análise de Concorrência'),'Petlove','petlove','marketplace','Marketplace pet e e-commerce nacional, com foco em produtos e modelo whitelabel, mas lacunas em serviços agendados, logística e gestão operacional completa para pequenos negócios.','E-commerce/marketplace pet nacional.'),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='ClickPet PitchDeck'),'Pet shops locais','petshops-locais','informal_channel','Pet shops independentes com operação local, mas baixa integração digital, atendimento manual e dependência de canais informais.','Base pulverizada e público-alvo da ClickPet.');

INSERT INTO competitor_analysis (company_id, competitor_id, source_id, comparison_dimension, competitor_strength, competitor_weakness, clickpet_advantage, threat_level, opportunity_for_clickpet, strategic_note, display_order)
VALUES
('11111111-1111-1111-1111-111111111111',(SELECT id FROM competitors WHERE slug='ifood'),(SELECT id FROM institutional_sources WHERE title='ClickPet - Análise de Concorrência'),'Delivery generalista','Grande base de clientes, parceiros cadastrados, infraestrutura de delivery e marca forte.','Comissão elevada, pet shop é apenas mais uma categoria, sem gestão de agenda, banho, tosa, serviços ou catálogo especializado.','Plataforma 100% dedicada ao ecossistema pet, com dashboard completo, agenda, status, métricas e gestão de parceiros de entrega.', 'medium','Capturar lojistas que precisam de operação pet vertical, não apenas entrega.', 'Material cita comissão iFood de 12% a 31% e comissão média de 28,7%.',1),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM competitors WHERE slug='aiqfome'),(SELECT id FROM institutional_sources WHERE title='ClickPet - Análise de Concorrência'),'Delivery regional generalista','Presença em cidades do interior e operação ligada ao Grupo Magalu.','Não oferece gestão especializada de pet shop, serviços, agenda e logística pet dedicada.','Modelo especializado com foco em produtos, serviços, agenda e relacionamento do pet shop.', 'medium','Entrar em regiões onde apps generalistas atendem demanda sem resolver operação do lojista.', 'Aiqfome é tratado como concorrente indireto generalista.',2),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM competitors WHERE slug='grupo-petz-cobasi'),(SELECT id FROM institutional_sources WHERE title='ClickPet - Análise de Concorrência'),'Grande rede varejista','Marca forte, lojas físicas, e-commerce e escala nacional.','Foco em produto e lojas próprias; não habilita pet shops independentes com logística integrada e não alcança o mercado fragmentado de pequenos negócios locais.','A ClickPet atua como infraestrutura para pet shops independentes e pode digitalizar o segmento oposto ao das megastores.', 'high','Fortalecer lojas locais contra redes nacionais por meio de tecnologia acessível.', 'Material cita R$ 7,9 bi de faturamento 2025, 500+ lojas físicas, ~11% de market share e 140+ cidades atendidas.',3),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM competitors WHERE slug='petlove'),(SELECT id FROM institutional_sources WHERE title='ClickPet - Análise de Concorrência'),'Marketplace pet','Marca nacional, marketplace e presença digital no setor pet.','Foco em produto, não em serviços agendados como banho, tosa e leva e traz; whitelabel básico sem gestão de agenda, pedidos, logística ou entregadores; exige CNPJ ativo e exclui parte de pequenos negócios.','A ClickPet entrega produto, serviço, agenda e logística em uma plataforma vertical completa.', 'high','Atender lacunas operacionais dos pequenos pet shops e serviços locais.', 'Material cita R$ 2,45 bi de receita projetada 2025, +38% crescimento esperado, 4 mil+ petshops parceiros whitelabel e 89 mil pets com seguro de saúde.',4),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM competitors WHERE slug='petshops-locais'),(SELECT id FROM institutional_sources WHERE title='ClickPet PitchDeck'),'Operação local informal','Proximidade local, relacionamento com clientes e conhecimento da região.','Baixa integração, baixa experiência digital, pouca transparência, dependência de WhatsApp e processos manuais.','A ClickPet transforma esses estabelecimentos em operações digitais sem competir diretamente com eles.', 'low','Converter concorrência fragmentada em base parceira da plataforma.', 'Pet shops locais são principalmente público-alvo e oferta da plataforma, não ameaça direta.',5);

INSERT INTO competitive_advantages (company_id, source_id, advantage_name, advantage_summary, advantage_detail, defensibility_level, investor_relevance, display_order)
VALUES
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'Foco em pequenos e médios pet shops','A ClickPet é desenhada para o segmento independente pouco digitalizado.','Grandes redes vendem para o consumidor final; a ClickPet fornece infraestrutura para pet shops independentes competirem digitalmente.', 'medium','Cria posicionamento claro e reduz conflito com lojistas.',1),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'Plataforma pronta para operação','Baixo custo de entrada para lojistas.','Pet shops não precisam desenvolver tecnologia própria para vender online, gerir pedidos e se conectar com consumidores.', 'medium','Acelera adoção e reduz barreiras comerciais.',2),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='ClickPet PitchDeck'),'Integração absoluta da jornada','Compra, serviço, entrega e experiência em uma jornada fluida.','O Pitch Deck posiciona a ClickPet como camada de inteligência que unifica compra, serviço, entrega e experiência para o bem-estar animal.', 'high','Diferencia a plataforma de apps generalistas, marketplaces e lojas isoladas.',3),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'Marketplace especializado','Ambiente dedicado ao ecossistema pet.','A especialização permite linguagem, funcionalidades e operação voltadas para comportamento e necessidades do setor pet.', 'medium','Aumenta relevância para lojistas e consumidores do nicho.',4),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'Arquitetura preparada para expansão nacional','Modelo pode ser replicado em novas regiões.','A combinação de plataforma, parceiros locais e marketplace regional permite expansão progressiva para outros mercados.', 'medium','Sustenta tese de escala e retorno de venture capital.',5);

-- =========================
-- RISKS AND FAQ
-- =========================

INSERT INTO risks (company_id, source_id, risk_name, risk_summary, risk_detail, risk_level, mitigation_strategy, investor_note, display_order)
VALUES
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'Velocidade de aquisição de clientes','Risco de crescimento comercial mais lento que o previsto.','A empresa precisa adquirir pet shops cadastrados e ativos para validar o modelo e iniciar geração de receita recorrente.', 'high','Uso da rodada para marketing, aquisição, expansão comercial, prospecção ativa e parcerias estratégicas.', 'Principal risco da etapa Pré-Seed está na execução comercial.',1),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'Adoção pelos estabelecimentos','Pet shops podem ter resistência operacional ou baixa maturidade digital.','A adoção depende de onboarding simples, valor percebido rápido e suporte à mudança de processos manuais.', 'medium','Plataforma pronta para operação, baixo custo de entrada e foco em resolver dores operacionais do lojista.', 'Risco típico de transformação digital em PME.',2),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'Necessidade de capital para expansão','Escala comercial e evolução de produto exigem capital.','Marketing, tecnologia, equipe comercial e expansão regional dependem de investimento externo.', 'medium','Captação proposta de R$ 500.000 com alocação clara por área.', 'Rodada busca financiar validação e crescimento inicial.',3),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'Aumento da concorrência','Players maiores podem ampliar atuação no setor pet.','Apps generalistas, varejistas e marketplaces podem investir em soluções específicas para o setor.', 'medium','Especialização vertical, relacionamento com pet shops independentes e execução rápida em nichos locais.', 'Defensibilidade dependerá de base de parceiros, dados, operação local e produto especializado.',4);

INSERT INTO investor_faqs (company_id, source_id, question, short_answer, detailed_answer, category, display_order, tags)
VALUES
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'O que é a ClickPet?','A ClickPet é uma plataforma B2B2C para digitalizar pet shops independentes.','Ela oferece aplicativo para consumidores, painel administrativo para lojistas, catálogo digital, marketplace regional, gestão de pedidos e integração entre consumidores e estabelecimentos pet.', 'company',1,ARRAY['empresa','resumo']),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'Qual problema a ClickPet resolve?','Resolve a baixa digitalização e fragmentação operacional dos pet shops independentes.','Muitos pet shops dependem de WhatsApp, Instagram, atendimento manual e baixa presença digital, perdendo competitividade para redes e marketplaces maiores.', 'problem',2,ARRAY['problema','mercado']),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'Como a ClickPet ganha dinheiro?','A principal receita prevista é comissão sobre vendas realizadas na plataforma.','No médio e longo prazo, a empresa também poderá monetizar por planos premium, publicidade interna, serviços financeiros, logística integrada e ferramentas de marketing para lojistas.', 'business_model',3,ARRAY['receita','modelo-de-negocio']),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'Qual é o estágio atual da empresa?','A empresa está em estágio Pré-Seed, com MVP concluído e plataforma operacional.','O memo informa MVP concluído, aplicativo publicado, website operacional, infraestrutura própria e primeiros pet shops utilizando a solução.', 'traction',4,ARRAY['tracao','status']),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'Qual é a rodada de investimento?','Rodada Pré-Seed de R$ 500.000 com valuation pré-money proposto de R$ 3.200.000.','A rodada propõe valuation pós-money de R$ 3.700.000 e participação ofertada de 13,5%.', 'funding',5,ARRAY['rodada','valuation']),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'Como os recursos serão usados?','40% produto e tecnologia, 30% marketing e aquisição, 20% expansão comercial e 10% capital de giro.','A distribuição busca fortalecer produto, acelerar aquisição, validar canais comerciais e dar sustentação operacional à fase de crescimento.', 'funding',6,ARRAY['uso-dos-recursos','captação']),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'Quais são os diferenciais competitivos?','Foco em pet shops independentes, plataforma pronta para operação, marketplace especializado e integração da jornada pet.','A ClickPet se posiciona como parceiro tecnológico dos lojistas, integrando consumidor, catálogo, pedidos, serviços, agenda, logística e gestão operacional.', 'competition',7,ARRAY['diferenciais','concorrencia']),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'Quais são os principais riscos?','Aquisição de clientes, adoção dos estabelecimentos, necessidade de capital e aumento da concorrência.','Esses riscos são parcialmente mitigados pelo produto já desenvolvido, MVP funcional, plataforma operacional, primeiros usuários e tendência de digitalização do setor pet.', 'risk',8,ARRAY['riscos']),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='Investment Memo ClickPet'),'Qual é a visão de longo prazo?','Construir a principal infraestrutura digital para pet shops independentes no Brasil.','A visão é consolidar um ecossistema que conecte consumidores, estabelecimentos e tecnologia em uma plataforma única, ampliando a competitividade das lojas parceiras.', 'vision',9,ARRAY['visao','longo-prazo']),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='ClickPet - Análise de Concorrência'),'Por que investir agora?','Porque o produto já existe, o mercado é grande e a digitalização de pet shops independentes ainda está em estágio inicial.','A rodada financia a transição de produto validado tecnicamente para validação comercial e expansão, em um mercado recorrente com lacuna clara entre consumidores digitais e lojistas locais pouco estruturados.', 'investment_thesis',10,ARRAY['tese','investimento']);

-- Flexible retrieval entries for AI natural-language answers.
INSERT INTO knowledge_entries (company_id, source_id, category, title, answer_summary, answer_detail, investor_relevance, confidence_score, tags)
VALUES
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='ClickPet PitchDeck'),'company','Origem da ClickPet','A ClickPet nasceu de uma dor real: compras e serviços pet fragmentados.','O Pitch Deck apresenta a origem da ClickPet em etapas: insight inicial sobre a dificuldade de donos de pets com compras e serviços fragmentados; validação por análise de mercado e comportamento do consumidor; estruturação da operação, parceiros e serviços; ideação do conceito; desenvolvimento do modelo de negócio e experiência do usuário; e momento ideal de lançamento com foco em escalabilidade.', 'Ajuda investidores a entenderem a evolução lógica da oportunidade, da dor ao produto.',0.95,ARRAY['origem','historia','pitch']),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='ClickPet - Análise de Concorrência'),'market','Oportunidade no mercado fragmentado','48,7% do mercado está nas mãos de pequenos e médios pet shops locais segundo o material de concorrência.','A análise aponta que esse segmento fatura aproximadamente R$ 37,5 bilhões ao ano sem uma plataforma especializada de gestão e delivery integrados, formando a oportunidade central para a ClickPet.', 'Dimensiona o segmento-alvo e sustenta a tese de mercado.',0.90,ARRAY['mercado','pme','oportunidade']),
('11111111-1111-1111-1111-111111111111',(SELECT id FROM institutional_sources WHERE title='ClickPet - Apresentação de Projeto'),'product','Produto como infraestrutura para lojistas','A ClickPet oferece ferramentas operacionais que vão além da vitrine digital.','A apresentação de projeto descreve dashboard de vendas, pedidos, produtos, agenda, cupons, entregadores, assinatura/licenciamento e parametrização de regras operacionais, mostrando que a proposta é infraestrutura de operação, não apenas uma página de produtos.', 'Evidencia profundidade de produto e potencial de retenção B2B.',0.95,ARRAY['produto','dashboard','lojistas']);

REFRESH MATERIALIZED VIEW investor_search_index;

COMMIT;
